"""Generic runtime boundaries for the PYNQ NPU overlay."""

from .npu import NPURuntime, PhysicalJobMetrics, load_pynq_runtime
from .lowering import (
    LoweringMetrics,
    LoweringResult,
    LoweringValidationError,
    MatrixTileError,
    MatrixLowerer,
)
from .model import (
    LoadedModel,
    ModelExecutionError,
    ModelLoadError,
    ModelMetrics,
    ModelResult,
    ModelRuntimeError,
    NPUModelRuntime,
    load_model_package,
)
from .acceptance import AcceptanceRunError, run_resnet18_acceptance
from .benchmark import (
    BENCHMARK_MAGIC,
    BenchmarkError,
    HostMatrixEngine,
    MatrixPoint,
    Provenance,
    build_record,
    compare_int8_to_float,
    compare_records,
    load_record,
    measure_matrix_point,
    publish_record,
    run_matrix_sweep,
    summarize_model_run,
)

__all__ = [
    "NPURuntime",
    "PhysicalJobMetrics",
    "load_pynq_runtime",
    "LoweringMetrics",
    "LoweringResult",
    "LoweringValidationError",
    "MatrixTileError",
    "MatrixLowerer",
    "LoadedModel",
    "ModelExecutionError",
    "ModelLoadError",
    "ModelMetrics",
    "ModelResult",
    "ModelRuntimeError",
    "NPUModelRuntime",
    "load_model_package",
    "AcceptanceRunError",
    "run_resnet18_acceptance",
    "BENCHMARK_MAGIC",
    "BenchmarkError",
    "HostMatrixEngine",
    "MatrixPoint",
    "Provenance",
    "build_record",
    "compare_int8_to_float",
    "compare_records",
    "load_record",
    "measure_matrix_point",
    "publish_record",
    "run_matrix_sweep",
    "summarize_model_run",
]
