"""Generate the instruction-stream vectors for tb_npu_isa_frontend.

Each case is a memory image holding a program (at physical address 0) and the
data region it computes on (at DATA_BASE), plus the image the golden ISA
simulator leaves behind. The testbench loads the first image into its AXI
memory model, runs the program on the full npu_accelerator, and compares
every word of memory with the second image.

    python -m src.test.vectors.generate_isa_vectors [--check]
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from src.isa import isa, layout, sim

OUTPUT = Path(__file__).with_name("isa_frontend_16x16.txt")
LIMITS = isa.Limits(rows=16, columns=16, max_k=256)
SEED = 0x15A


def _gemm_case(rng, m, n, k, tk=None):
    a = rng.integers(-128, 128, (m, k), dtype=np.int8)
    b = rng.integers(-128, 128, (k, n), dtype=np.int8)
    plan = layout.plan_gemm(m, n, k, LIMITS, tk)
    a_base = 0
    b_base = isa.align(plan.a_bytes, 64)
    c_base = b_base + isa.align(plan.b_bytes, 64)
    data = np.zeros(c_base + plan.c_bytes, np.uint8)
    data[a_base:a_base + plan.a_bytes] = layout.pack_a(plan, a).view(np.uint8)
    data[b_base:b_base + plan.b_bytes] = layout.pack_b(plan, b).view(np.uint8)
    # Poison the result region so a missed store cannot pass.
    data[c_base:] = 0xA5
    program = layout.encode(plan, a_base, b_base, c_base) + [isa.end()]
    return program, data, plan.jobs


def _image(program, data):
    prog_bytes = len(program) * 8
    data_base = isa.align(prog_bytes + 8, 256)
    image = np.zeros(isa.align(data_base + data.size, 8), np.uint8)
    image[:prog_bytes] = np.frombuffer(isa.pack(program), np.uint8)
    image[data_base:data_base + data.size] = data
    return image, data_base


def build_cases():
    rng = np.random.default_rng(SEED)
    cases = []
    for m, n, k, tk in [(16, 16, 256, None), (5, 37, 300, None), (1, 49, 40, None),
                        (33, 20, 320, 128), (3, 3, 7, None)]:
        program, data, jobs = _gemm_case(rng, m, n, k, tk)
        image, data_base = _image(program, data)
        expected = image.copy()
        sim.run(program, expected[data_base:], LIMITS)
        cases.append((f"gemm_{m}x{n}x{k}", image, expected, len(program), data_base, 0, jobs))
    # An illegal opcode stops the program after the jobs before it retire.
    program, data, jobs = _gemm_case(rng, 4, 8, 16)
    program = program[:-1] + [0x7F << 56, isa.end()]
    image, data_base = _image(program, data)
    expected = image.copy()
    sim.run(program[:-2] + [isa.end()], expected[data_base:], LIMITS)
    cases.append(("illegal_opcode", image, expected, len(program), data_base, isa.ERR_ILLEGAL_OPCODE, jobs))
    # A shape beyond the array is refused before any job issues.
    program = [isa.shape(4, 17, 8), isa.gemm(), isa.end()]
    image, data_base = _image(program, np.zeros(64, np.uint8))
    cases.append(("bad_shape", image, image.copy(), len(program), data_base, isa.ERR_BAD_SHAPE, 0))
    return cases


def render() -> str:
    lines = [f"# generated by src/test/vectors/generate_isa_vectors.py, seed 0x{SEED:x}"]
    for name, image, expected, prog_len, data_base, error, jobs in build_cases():
        words = image.size // 8
        lines.append(f"case {words} {prog_len} {data_base} {error} {jobs} {name}")
        lines.extend(f"{w:016x}" for w in image.view("<u8"))
        lines.extend(f"{w:016x}" for w in expected.view("<u8"))
    lines.append("end 0 0 0 0 0 none")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()
    text = render()
    if args.check:
        if OUTPUT.read_text() != text:
            print(f"{OUTPUT} is stale; regenerate it")
            return 1
        return 0
    OUTPUT.write_text(text)
    print(f"wrote {OUTPUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
