import { createHash, randomUUID } from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import { access, chmod, mkdir, open, readFile, rename, rm, stat, writeFile } from 'node:fs/promises';
import { homedir, hostname } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Readable, Transform } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { spawn } from 'node:child_process';
import { setTimeout as sleep } from 'node:timers/promises';
import * as tar from 'tar';

export const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(await readFile(new URL('./toolchains.json', import.meta.url), 'utf8'));
const dependencyLock = await readFile(new URL('./requirements.lock', import.meta.url));
export const log = message => process.stderr.write(`[ic-tools] ${message}\n`);
export const exists = async p => access(p).then(() => true, () => false);
export const openroadImage = manifest.openroad.image;
export const openroadPlatform = manifest.openroad.platform;

const dockerOpenroadWrapper = `#!/usr/bin/env python3
# Generated by @jony2156/ai-eda-tools. Regenerate with ic-tools setup.
import json
import os
import sys

image = os.environ.get("IC_OPENROAD_DOCKER_IMAGE")
if not image:
    raise SystemExit("IC_OPENROAD_DOCKER_IMAGE is not set")
platform = os.environ.get("IC_OPENROAD_DOCKER_PLATFORM", "linux/amd64")

mounts = json.loads(os.environ.get("IC_OPENROAD_MOUNTS", "[]"))
mounts.append(os.getcwd())
command = ["docker", "run", "--rm", "--platform", platform]
if hasattr(os, "getuid"):
    command.extend(["--user", "%s:%s" % (os.getuid(), os.getgid())])
for source in dict.fromkeys(os.path.realpath(item) for item in mounts):
    if source == "/" or ":" in source or "\\n" in source:
        raise SystemExit("unsafe OpenROAD Docker mount: " + source)
    command.extend(["-v", source + ":" + source])
command.extend(["-w", os.getcwd(), image, "openroad", *sys.argv[1:]])
os.execvp("docker", command)
`;

export function platformSpec(platform = process.platform, arch = process.arch) {
  const key = `${platform}-${arch}`;
  const asset = manifest.platforms[key];
  if (!asset) throw new Error(`Unsupported platform ${key}. On Windows, install Node.js and run this package inside WSL. Supported: ${Object.keys(manifest.platforms).join(', ')}.`);
  const name = `oss-cad-suite-${key}-${manifest.release.replaceAll('-', '')}.tgz`;
  return { ...asset, key, name, url: `${manifest.source}/releases/download/${manifest.release}/${name}` };
}

export function cacheRoot(env = process.env) {
  return path.resolve(env.IC_MCP_CACHE || (process.platform === 'darwin'
    ? path.join(homedir(), 'Library', 'Caches', 'ic-tools')
    : path.join(env.XDG_CACHE_HOME || path.join(homedir(), '.cache'), 'ic-tools')));
}

export function runtimeKey(spec) {
  return `${manifest.release}-${spec.key}-${createHash('sha256').update(spec.sha256).update(dependencyLock).update('bootstrap-v1').digest('hex').slice(0, 16)}`;
}

export async function sha256(file) {
  const hash = createHash('sha256');
  for await (const chunk of createReadStream(file)) hash.update(chunk);
  return hash.digest('hex');
}

export async function verify(file, spec) {
  if ((await stat(file)).size !== spec.size || await sha256(file) !== spec.sha256)
    throw new Error(`Integrity check failed for ${file}. Expected SHA256 ${spec.sha256}. Remove the corrupt archive and retry setup.`);
}

export async function download(spec, destination, { fetchImpl = fetch } = {}) {
  if (await exists(destination)) { await verify(destination, spec); return destination; }
  await mkdir(path.dirname(destination), { recursive: true });
  const temp = `${destination}.${randomUUID()}.part`;
  try {
    log(`Downloading ${spec.name} (${Math.ceil(spec.size / 1024 / 1024)} MiB)`);
    if (new URL(spec.url).protocol !== 'https:') throw new Error('Toolchain downloads require HTTPS.');
    const response = await fetchImpl(spec.url, { signal: AbortSignal.timeout(20 * 60 * 1000) });
    if (!response.ok || !response.body) throw new Error(`Download failed: HTTP ${response.status}`);
    if (response.url && new URL(response.url).protocol !== 'https:') throw new Error('Refusing a non-HTTPS redirect.');
    let bytes = 0;
    let lastNotice = Date.now();
    const meter = new Transform({ transform(chunk, _, callback) {
      bytes += chunk.length;
      if (bytes > spec.size) return callback(new Error('Archive exceeds its pinned size.'));
      if (Date.now() - lastNotice > 15000) { log(`Downloaded ${Math.floor(bytes / 1024 / 1024)} MiB`); lastNotice = Date.now(); }
      callback(null, chunk);
    } });
    await pipeline(Readable.fromWeb(response.body), meter, createWriteStream(temp, { flags: 'wx' }));
    await verify(temp, spec);
    await rename(temp, destination);
    return destination;
  } finally { await rm(temp, { force: true }); }
}

export async function withLock(lockPath, action, { timeoutMs = 30 * 60 * 1000, pollMs = 500 } = {}) {
  await mkdir(path.dirname(lockPath), { recursive: true });
  const start = Date.now();
  let handle;
  while (!handle) {
    try { handle = await open(lockPath, 'wx', 0o600); }
    catch (error) {
      if (error.code !== 'EEXIST') throw error;
      const owner = await readFile(lockPath, 'utf8').then(JSON.parse).catch(() => null);
      if (owner?.host === hostname() && Number.isInteger(owner.pid)) {
        try { process.kill(owner.pid, 0); }
        catch (e) { if (e.code === 'ESRCH') throw new Error(`Interrupted setup lock: ${lockPath}. Its process ${owner.pid} has exited. Remove this lock file and retry setup.`); }
      }
      if (Date.now() - start >= timeoutMs) throw new Error(`Timed out waiting for setup lock ${lockPath}. Check the owning installer before removing it.`);
      await sleep(pollMs);
    }
  }
  try {
    await handle.writeFile(JSON.stringify({ pid: process.pid, host: hostname() }));
    return await action();
  } finally { await handle.close(); await rm(lockPath, { force: true }); }
}

export async function extract(archive, destination) {
  await mkdir(destination, { recursive: true });
  const invalid = [];
  // Validate the complete archive before invoking the platform tar. OSS CAD Suite
  // contains directory aliases that node-tar's extractor deliberately refuses.
  await tar.t({ file: archive, strict: true,
    filter: (name, entry) => {
      const normalized = path.posix.normalize(name);
      if (!(normalized === 'oss-cad-suite' || normalized.startsWith('oss-cad-suite/')) || name.includes('\\'))
        { invalid.push(`Invalid archive member: ${name}`); return false; }
      if (entry.linkpath) {
        const target = entry.type === 'Link' ? entry.linkpath : path.posix.join(path.posix.dirname(name), entry.linkpath);
        const resolved = path.posix.normalize(target);
        if (path.posix.isAbsolute(entry.linkpath) || !(resolved === 'oss-cad-suite' || resolved.startsWith('oss-cad-suite/')))
          { invalid.push(`Archive link escapes the toolchain: ${name} -> ${entry.linkpath}`); return false; }
      }
      return true;
    },
  });
  if (invalid.length) throw new Error(invalid.slice(0, 3).join('; '));
  await checked('tar', ['-xzf', archive, '-C', destination]);
}

export function runtimeEnvironment(runtime, env = process.env) {
  const suite = path.join(runtime, 'oss-cad-suite');
  const result = { ...env,
    PATH: [path.join(suite, 'bin'), path.join(suite, 'py3bin'), env.PATH || ''].join(path.delimiter),
    PYTHONPATH: [packageRoot, path.join(runtime, 'python-packages')].join(path.delimiter),
    PYTHONNOUSERSITE: '1', PYTHONDONTWRITEBYTECODE: '1',
    VERILATOR_ROOT: path.join(suite, 'share', 'verilator'),
    VIRTUAL_ENV: suite,
  };
  delete result.PYTHONHOME;
  return result;
}

export function pythonPath(runtime) { return path.join(runtime, 'oss-cad-suite', 'py3bin', 'python3'); }

// Bootstrap child output goes to stderr; only the final MCP process gets stdout.
export function run(command, args, { env = process.env, cwd = process.cwd(), mcp = false } = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { env, cwd, stdio: mcp ? 'inherit' : ['ignore', 2, 2] });
    const onInt = () => child.kill('SIGINT');
    const onTerm = () => child.kill('SIGTERM');
    process.on('SIGINT', onInt); process.on('SIGTERM', onTerm);
    const cleanup = () => { process.off('SIGINT', onInt); process.off('SIGTERM', onTerm); };
    child.once('error', error => { cleanup(); reject(error); });
    child.once('exit', (code, signal) => { cleanup(); resolve(code ?? (signal === 'SIGINT' ? 130 : 143)); });
  });
}

export async function checked(command, args, options) {
  const code = await run(command, args, options);
  if (code !== 0) throw new Error(`${path.basename(command)} exited ${code}. See diagnostics above.`);
}

async function exitsZero(runImpl, command, args, env) {
  try { return await runImpl(command, args, { env }) === 0; }
  catch { return false; }
}

export async function requireOpenroad({ env = process.env, runImpl = run } = {}) {
  const mode = env.IC_OPENROAD_MODE || 'auto';
  if (!['auto', 'host', 'docker'].includes(mode))
    throw new Error(`Invalid IC_OPENROAD_MODE=${mode}. Expected auto, host or docker.`);

  if (mode !== 'docker' && await exitsZero(runImpl, 'openroad', ['-version'], env)) {
    env.IC_OPENROAD_PROVIDER = 'host';
    delete env.IC_OPENROAD_DOCKER_IMAGE;
    delete env.IC_OPENROAD_DOCKER_PLATFORM;
    return { kind: 'host' };
  }
  if (mode === 'host')
    throw new Error('IC_OPENROAD_MODE=host requires `openroad` on PATH. See https://openroad.readthedocs.io/en/latest/user/Build.html');

  if (!await exitsZero(runImpl, 'docker', ['version', '--format', '{{.Server.Version}}'], env))
    throw new Error('OpenROAD was not found on PATH and Docker is unavailable. Install OpenROAD or start Docker, then retry setup. See https://openroad.readthedocs.io/en/latest/user/Build.html');

  if (!await exitsZero(runImpl, 'docker', ['image', 'inspect', openroadImage], env)) {
    log(`Pulling OpenROAD Docker image ${manifest.openroad.tag} (${openroadPlatform})`);
    if (!await exitsZero(runImpl, 'docker', ['pull', '--platform', openroadPlatform, openroadImage], env))
      throw new Error(`Could not pull the pinned OpenROAD image ${openroadImage}. Check Docker access and retry setup.`);
  }
  if (!await exitsZero(runImpl, 'docker', ['run', '--rm', '--platform', openroadPlatform, openroadImage, 'openroad', '-version'], env))
    throw new Error(`The OpenROAD image ${openroadImage} was pulled but failed its version check.`);

  env.IC_OPENROAD_PROVIDER = 'docker';
  env.IC_OPENROAD_DOCKER_IMAGE = openroadImage;
  env.IC_OPENROAD_DOCKER_PLATFORM = openroadPlatform;
  return { kind: 'docker', image: openroadImage, platform: openroadPlatform };
}

export async function configureOpenroad(runtime, provider) {
  if (!provider) return;
  const wrapper = path.join(runtime, 'oss-cad-suite', 'bin', 'openroad');
  const existing = await readFile(wrapper, 'utf8').catch(() => '');
  const generated = existing.includes('Generated by @jony2156/ai-eda-tools');
  if (provider.kind === 'host') {
    if (generated) await rm(wrapper, { force: true });
    return;
  }
  if (existing && !generated)
    throw new Error(`Refusing to replace an existing OpenROAD executable at ${wrapper}.`);
  await mkdir(path.dirname(wrapper), { recursive: true });
  await writeFile(wrapper, dockerOpenroadWrapper, { mode: 0o755 });
  await chmod(wrapper, 0o755);
}

export async function completed(runtime, key) {
  const marker = await readFile(path.join(runtime, 'complete.json'), 'utf8').then(JSON.parse).catch(() => null);
  return marker?.key === key && await exists(pythonPath(runtime)) && await exists(path.join(runtime, 'python-packages', 'mcp', '__init__.py'));
}

export async function ensureRuntime({
  root = cacheRoot(), spec = platformSpec(), install = installRuntime,
  requireTools = requireOpenroad,
} = {}) {
  // Prefer a native executable; otherwise use the pinned official ORFS image.
  // The provider check runs even for cached runtimes so a stopped Docker daemon
  // or removed host executable fails before the MCP server starts.
  const openroad = await requireTools();
  const key = runtimeKey(spec);
  const runtime = path.join(root, key);
  if (await completed(runtime, key)) {
    await configureOpenroad(runtime, openroad);
    return runtime;
  }
  return withLock(path.join(root, `${key}.lock`), async () => {
    if (await completed(runtime, key)) {
      await configureOpenroad(runtime, openroad);
      return runtime;
    }
    if (await exists(runtime)) throw new Error(`Incomplete runtime at ${runtime}. Move it aside and rerun setup.`);
    const stage = path.join(root, `${key}.staging-${randomUUID()}`);
    await mkdir(stage, { recursive: true });
    try {
      await install(stage, root, spec, openroad);
      await writeFile(path.join(stage, 'complete.json'), JSON.stringify({ key, release: manifest.release, platform: spec.key }));
      await rename(stage, runtime);
      return runtime;
    } finally { await rm(stage, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 }).catch(error => log(`Could not remove staging directory ${stage}: ${error.message}`)); }
  });
}

async function installRuntime(stage, root, spec, openroad) {
  let archive = process.env.IC_MCP_ARCHIVE;
  if (archive) { archive = path.resolve(archive); await verify(archive, spec); }
  else archive = await download(spec, path.join(root, 'downloads', spec.name));
  log('Extracting the verified toolchain');
  await extract(archive, stage);
  await configureOpenroad(stage, openroad);
  const env = runtimeEnvironment(stage);
  const python = pythonPath(stage);
  log('Installing hash-locked Python dependencies');
  // The lock pins the full dependency closure, so pip must not re-resolve dependency specifiers:
  // the bundled pip 23.2 treats an extra such as mcp's pyjwt[crypto] as unpinned and fetches the
  // newest release, which --require-hashes then rejects.
  await checked(python, ['-m', 'pip', '--isolated', '--disable-pip-version-check', 'install', '--no-user',
    '--require-hashes', '--no-deps', '--only-binary=:all:', '--target', path.join(stage, 'python-packages'),
    '-r', path.join(packageRoot, 'npm', 'requirements.lock')], { env });
  await checked(python, ['-c', 'import mcp, pydantic; from ic_mcp.server import build_server; build_server()'], { env });
  await checked(python, ['-m', 'ic_cli.main', 'doctor'], { env });
  log('Runtime ready');
}
