"""Production-visible numeric and graph contracts for NPU model tooling."""

from .numeric import (
    INT8_MAX,
    INT8_MIN,
    INT32_MAX,
    INT32_MIN,
    mac_int8_int32,
    matmul_int8,
    requantize_int32_to_int8,
    round_ratio_away_from_zero,
    saturate_int8,
    saturate_int32,
    saturating_add_int32,
)
from .resnet import (
    ConstantTensor,
    Conv2D,
    Flatten,
    FullyConnected,
    GlobalAveragePool,
    GraphValidationError,
    MaxPool,
    Quantization,
    QuantizedGraph,
    Relu,
    ResidualAdd,
    TensorSpec,
)
from .operators import (
    conv2d_int8,
    flatten_int8,
    fully_connected_int8,
    global_average_pool_int8,
    max_pool_int8,
    relu_int8,
    residual_add_int8,
)

__all__ = [
    "INT8_MAX",
    "INT8_MIN",
    "INT32_MAX",
    "INT32_MIN",
    "mac_int8_int32",
    "matmul_int8",
    "requantize_int32_to_int8",
    "round_ratio_away_from_zero",
    "saturate_int8",
    "saturate_int32",
    "saturating_add_int32",
    "ConstantTensor",
    "Conv2D",
    "Flatten",
    "FullyConnected",
    "GlobalAveragePool",
    "GraphValidationError",
    "MaxPool",
    "Quantization",
    "QuantizedGraph",
    "Relu",
    "ResidualAdd",
    "TensorSpec",
    "conv2d_int8",
    "flatten_int8",
    "fully_connected_int8",
    "global_average_pool_int8",
    "max_pool_int8",
    "relu_int8",
    "residual_add_int8",
]
