"""Waveform tracing without touching the testbench.

Verilator writes a trace only when the testbench calls `$dumpfile`/`$dumpvars`.
The existing testbenches in this repository do not, and editing eight of them
to add dump calls would mean the tools changed the design they were meant to
observe.

Instead a one-module probe file is generated per run and bound into the
testbench, so the dump calls execute as if the testbench had made them while
the checked-in sources stay untouched:

    module ic_trace_probe;
      initial begin $dumpfile("wave.fst"); $dumpvars(0); end
    endmodule
    bind tb_npu_pe ic_trace_probe ic_trace_probe_i();

`bind` is IEEE 1800 and is supported by both Verilator 5 and Icarus 11.
"""

from __future__ import annotations

from pathlib import Path


def write(directory: Path, tb_module: str, wave_file: str) -> Path:
    path = directory / "ic_trace_probe.sv"
    path.write_text(
        "// Generated by ic sim. Not part of the design.\n"
        "module ic_trace_probe;\n"
        "  initial begin\n"
        f'    $dumpfile("{wave_file}");\n'
        "    $dumpvars(0);\n"
        "  end\n"
        "endmodule\n"
        f"bind {tb_module} ic_trace_probe ic_trace_probe_i();\n"
    )
    return path
